# -*- coding: utf-8 -*-
"""assignment_7_with_regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Evi0ZgizFDU08e-fRssaP_5sfKf0pUeH
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Names and PRN for all group members:
- Name: ______________________
- PRN:  ______________________
- Date: ______________________

# Image Processing with Neural Network
## A07: Group Assignment


##  Convolutional Neural Network (CNN)

- Flowers Dataset
"""

# Commented out IPython magic to ensure Python compatibility.
###-----------------
### Import Libraries
###-----------------
import os
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.metrics import accuracy_score,classification_report
from utils.helper import fn_plot_tf_hist, fn_plot_confusion_matrix,fn_plot_label


# %matplotlib inline

###----------------------
### Some basic parameters
###----------------------

# inpDir = Path('.') # location where input data is stored
# outDir = Path('.') # location to store outputs
subDir = 'flower_photos' # location of the images
modelDir = Path('../models') # location to save model files
valDir = 'valid_flowers' # location related to this dataset
altName = 'base_flowers' # Model file name for this alternative

RANDOM_STATE = 24 # for initialization ----- REMEMBER: to remove at the time of promotion to production
tf.random.set_seed(RANDOM_STATE)


EPOCHS = 100   # number of cycles to run
ALPHA = 0.001
BATCH_SIZE = 16
TEST_SIZE = 0.2
IMG_HEIGHT = 190
IMG_WIDTH = 190

# Transformations
# flipping
FLIP_MODE = "horizontal_and_vertical"
# Rotation
ROTATION_FACTOR = (-0.1, 0.1)
# filling mode
FILL_MODE = 'nearest'


## Early Stopping
ES_PATIENCE = 20 # if performance does not improve stop
# Learning rates
LR_PATIENCE = 10 # if performace is not improving reduce alpha
LR_FACTOR = 0.5 # rate of reduction of alpha


# Set parameters for decoration of plots
params = {'legend.fontsize' : 'large',
          'figure.figsize'  : (15,8),
          'axes.labelsize'  : 'x-large',
          'axes.titlesize'  :'x-large',
          'xtick.labelsize' :'large',
          'ytick.labelsize' :'large',
         }

CMAP = plt.cm.coolwarm

plt.rcParams.update(params) # update rcParams

"""## Basic Hygiene"""

# ###------------------
# ### Memory Management
# ###------------------

# physical_devices = tf.config.list_physical_devices('GPU')

# if len(physical_devices) > 0:
#     tf.config.experimental.set_memory_growth(physical_devices[0], True)
#     print (physical_devices)
# else:
#     print ('Error: No GPU device found')

"""## Helper Functions
**Note** all helper functions have been moved to util.helper

## Load Dataset

Images are under flower_photos

     |- daisy
     |- dandelion
     |- roses
     |- sunflowers
     |- tulips
"""

# '''
#     For reading from web link
# '''

# import pathlib
# dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
# data_dir = tf.keras.utils.get_file(origin=dataset_url,
#                                   fname='flower_photos',
#                                   untar=True)
# data_dir = pathlib.Path(data_dir) / 'flower_photos'
# # '''
# #     For reading from local directory
# # '''
# data_dir = os.path.join('/content/flower_photos')

# import tensorflow as tf
# import pathlib
# import os

# # Download and extract dataset
# dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
# data_dir = tf.keras.utils.get_file(
#     fname='flower_photos',
#     origin=dataset_url,
#     untar=True
# )

# # Convert to pathlib Path object for easy path operations
# data_dir = pathlib.Path(data_dir) / 'flower_photos'
# print(f"Dataset downloaded and extracted to: {data_dir}")

# # Example: load dataset using image_dataset_from_directory
# dataset = tf.keras.utils.image_dataset_from_directory(str(data_dir))

# # If you want to access the images later, you can list files like this:
# image_files = list(data_dir.glob('*/*.jpg'))
# print(f"Number of images: {len(image_files)}")

# # If you want to save or reference this directory within Colab session use this path:
# print(f"Local directory path in Colab: {data_dir}")

data_dir

# list content of data_dir
os.listdir(data_dir)

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split=TEST_SIZE,
    subset='training',
    seed= RANDOM_STATE,
    image_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split=TEST_SIZE,
    subset='validation',
    seed= RANDOM_STATE,
    image_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE)

"""### Is it picking the class names?"""

class_names = train_ds.class_names
num_classes = len(class_names)
print('total ', num_classes, class_names)

"""### Verify the data

To verify that the dataset looks correct, let's plot the first batch from the training set and display the class name below each image.

"""

# set figure size
fig = plt.figure()  # figure size in inches with default params

# Adjust the subplot layout parameters.
fig.subplots_adjust(left=0., # as a fraction of the figure width
                    right=1., # use full width, as a fraction of the figure width
                    bottom=0., # as a fraction of the figure height
                    top=1., # as a fraction of the figure height
                    hspace=0.05, # as a fraction of the average Axes height
                    wspace=0.05) # width of the padding between subplots

# take one batch of the dataset
for images, labels in train_ds.take(1):

    # iterate through the batch
    for i in range(BATCH_SIZE):

        # add a subplot
        ax = fig.add_subplot( BATCH_SIZE//8, 8, (i+1), xticks=[], yticks=[]) # add a subplot to the figure

        # image_size may have converted these images to float
        ax.imshow(images[i].numpy().astype("uint8"))

        # display class in the title
        ax.set_title(class_names[labels[i]])

# fit the subplot(s) in to the figure area
plt.tight_layout()

# display all open images
plt.show()

# how many examples in each of the class
fn_plot_label(train_ds, test_ds)

images[0].shape

# layer = tf.keras.layers.RandomZoom(height_factor = (-0.2,0.2),
#                              width_factor = (-0.2,0.2))

layer = tf.keras.layers.RandomRotation((-0.5,0.5),fill_mode='nearest')

plt.figure()
img_num = 0
for images,labels in train_ds.take(1):
    out_images = layer(images)
plt.subplot(1,2,1)
plt.title('original')
plt.imshow(images[img_num].numpy().astype('uint16'))

plt.subplot(1,2,2)
plt.title('output')
plt.imshow(out_images[img_num].numpy().astype('uint16'))

"""<h1>BUILD MODEL</h1>"""

input_shape = [IMG_HEIGHT,IMG_WIDTH,3]

def build_model(input_shape, num_classes):

    dor1 = 0.1
    dor2 = 0.2
    dor3 = 0.3
    dor4 = 0.4
    dor5 = 0.5
    dor6 = 0.6
    dor7 = 0.7


    model = tf.keras.Sequential()
    model.add(tf.keras.Input(shape = input_shape))
    model.add(tf.keras.layers.Rescaling(1./255))


    #set 1
    model.add(tf.keras.layers.Conv2D(32, (3,3))) #188 x 188 x 32
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.MaxPool2D()) # 94 x 94 x32
    model.add(tf.keras.layers.Dropout(dor1))

    #set 2
    model.add(tf.keras.layers.Conv2D(64, (3,3))) #92 x 92 x 64
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.MaxPool2D()) # 46 x 46 x64
    model.add(tf.keras.layers.Dropout(dor2))


    #set 3
    model.add(tf.keras.layers.Conv2D(128, (3,3))) #44 x 44 x 128
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.MaxPool2D()) # 22 x 22 x128
    model.add(tf.keras.layers.Dropout(dor3))


    #set 4
    model.add(tf.keras.layers.Conv2D(256, (3,3))) #20 x 20 x 256
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.MaxPool2D()) # 10 x 10 x256
    model.add(tf.keras.layers.Dropout(dor4))


    #set 5
    model.add(tf.keras.layers.Conv2D(512, (3,3))) # 8 x 8 x 512
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.MaxPool2D()) # 4 x 4 x512
    model.add(tf.keras.layers.Dropout(dor5))


    #set 6
    model.add(tf.keras.layers.Conv2D(1024, (3,3))) #2 x 2 x 1024
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.Dropout(dor6))
    model.add(tf.keras.layers.Flatten()) # 4096


    # Head
    model.add(tf.keras.layers.Dense(1024)) # 1024
    model.add(tf.keras.layers.ReLU())
    model.add(tf.keras.layers.Dropout(dor7))



    #Output
    model.add(tf.keras.layers.Dense(num_classes))





    return model
model = build_model(input_shape,num_classes)
model.summary()

#call backs
PATIENCE = 20
LR_FACTOR =0.1
LR_PATIENCE = 5
MIN_LR = 1e-6

es_callback = tf.keras.callbacks.EarlyStopping(monitor= 'val_loss',
                                              patience=PATIENCE,
                                              verbose = 1,
                                              restore_best_weights=True,
)

lr_callback = tf.keras.callbacks.ReduceLROnPlateau(
   monitor='val_loss',
    factor= LR_FACTOR,
    patience = LR_PATIENCE,
    verbose = 1,
    mode = 'auto',
    min_lr=MIN_LR
)

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam(learning_rate = ALPHA)
model.compile(optimizer = optimizer,
             loss = loss_fn,

             metrics = ['accuracy'])

history = model.fit(train_ds,
         validation_data=test_ds,
         epochs= EPOCHS,
         callbacks=[es_callback,lr_callback])

"""### Reload best Weights for evaluation"""







"""### Evaluate the model"""

loss_df = pd.DataFrame(history.history)
fn_plot_tf_hist(loss_df)

y_train = tf.concat([y for x, y in train_ds], axis=0).numpy()
print(y_train.shape)

yhat = model.predict(train_ds)
y_pred = yhat.argmax(axis=1)
print(f'Accuracy: {accuracy_score(y_train, y_pred):.5f}')
print(classification_report(y_train, y_pred))

y_train = tf.concat([y for x, y in train_ds], axis=0).numpy()
print(y_train.shape)

yhat = model.predict(train_ds)
y_pred = yhat.argmax(axis=1)
print(f'Accuracy: {accuracy_score(y_train, y_pred):.5f}')
print(classification_report(y_train, y_pred))

fn_plot_confusion_matrix(y_train, y_pred, class_names)

fig = plt.figure()
fig.subplots_adjust(left=0, right=1, bottom=0, top=1, hspace=0.05, wspace=0.05)

i=0
for images, labels in train_ds.take(1):
    yhat = model(images).numpy()
    y_pred = yhat.argmax(axis=1)
    for i in range(BATCH_SIZE):
        ax = fig.add_subplot(BATCH_SIZE//8, 8, (i+1), xticks=[], yticks=[])
        ax.grid(False)
        color = 'cyan'
        if y_pred[i] != labels[i]:
            color = 'red'
        props = dict(boxstyle = 'round',facecolor = color,alpha = 0.5)
        ax.imshow(images[i].numpy().astype('uint8'), cmap=plt.cm.binary, interpolation='nearest')
        # ax.text(2,4, str(labels[i].numpy()), color='b', fontsize=14)
        # ax.text(10,25, class_names[labels[i].numpy()], color='r', fontsize=10)
        ax.text(0.1,0.90,class_names[y_pred[i]],bbox = props,
               verticalalignment = 'top',
               transform = ax.transAxes,fontsize = 14)
        ax.set_title(class_names[labels[i].numpy()],fontsize = 14)
plt.tight_layout()
plt.show()

"""## Validate on the validation set"""

# loss, acc = model.evaluate(valid_ds)

# print('Accuracy score on Validation Data : {:.3f}%'.format( acc*100))

y_test = tf.concat([y for x, y in test_ds], axis=0).numpy()
print(y_test.shape)

yhat = model.predict(test_ds)
y_pred = yhat.argmax(axis=1)
print(f'Accuracy: {accuracy_score(y_test, y_pred):.5f}')
print(classification_report(y_test, y_pred))

fig = plt.figure()
fig.subplots_adjust(left=0, right=1, bottom=0, top=1, hspace=0.05, wspace=0.05)

i=0
for images, labels in test_ds.take(1):
    yhat = model(images).numpy()
    y_pred = yhat.argmax(axis=1)
    for i in range(BATCH_SIZE):
        ax = fig.add_subplot(BATCH_SIZE//8, 8, (i+1), xticks=[], yticks=[])
        ax.grid(False)
        color = 'cyan'
        if y_pred[i] != labels[i]:
            color = 'red'
        props = dict(boxstyle = 'round',facecolor = color,alpha = 0.5)
        ax.imshow(images[i].numpy().astype('uint8'), cmap=plt.cm.binary, interpolation='nearest')
        # ax.text(2,4, str(labels[i].numpy()), color='b', fontsize=14)
        # ax.text(10,25, class_names[labels[i].numpy()], color='r', fontsize=10)
        ax.text(0.1,0.90,class_names[y_pred[i]],bbox = props,
               verticalalignment = 'top',
               transform = ax.transAxes,fontsize = 14)
        ax.set_title(class_names[labels[i].numpy()],fontsize = 14)
plt.tight_layout()
plt.show()



